# -*- coding: utf-8 -*-
"""Problem3_22110114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imbVYXK-pHP_wcShGbag56pAc4fr1JFX
"""

import matplotlib.pyplot as plt

def solve_tdma(coeff, right_hand_side):

  def decomposition(coeff):
    n = len(coeff)
    u = coeff.copy()
    l = [[0 for i in range(n)] for j in range(n)]
    for i in range(n-1):
      a = coeff[i][i]
      b = coeff[i+1][i]
      f = (b/a)
      l[i][i] = 1
      l[i+1][i] = f
      for j in range(n):
        u[i+1][j] -= u[i][j]*f
    i += 1
    l[i][i] = 1
    return u, l

  def forward_substitution(l, right_hand_side):
    n = len(l)
    d = []
    d.append(right_hand_side[0])
    for i in range(1, n):
      d.append(right_hand_side[i] - l[i][i-1]*d[i-1])
    return d

  def backward_substitution(u, d):
    n = len(u)
    x = []
    x.append(d[-1] / u[n-1][n-1])
    for i in range(n-2, -1, -1):
      x.append((d[i] - u[i][i+1]*x[n-2-i]) / u[i][i])
    return x[::-1]

  u, l = decomposition(coeff)
  d = forward_substitution(l, right_hand_side)
  x = backward_substitution(u, d)

  return x

h = 0.1
x0 = 0
xf = 4
num_intervals = int((xf - x0) / h)
k = 5 * 10**-6
D = 1.5 * 10**-6

num_unknowns = num_intervals - 1

coefficient_matrix = []
right_hand_side_vector = []
for i in range(num_unknowns):
  coefficient_row = []
  if i == 0:
    right_hand_side_vector.append(0.1)
  else:
    right_hand_side_vector.append(0)
  for j in range(num_unknowns):
    if i == j:
      coefficient_row.append(2 + k/D * (h)**2)
    elif abs(i - j) == 1:
      coefficient_row.append(-1)
    else:
      coefficient_row.append(0)
  coefficient_matrix.append(coefficient_row)

concentration_values = [0.1]
concentration_values.extend(solve_tdma(coefficient_matrix, right_hand_side_vector))
concentration_values.append(0)

distances = [x0]
while x0 < xf:
  x0 += h
  distances.append(x0)

plt.plot(concentration_values)
plt.title("Concentration A vs distance")
plt.ylabel("Concentration of A in M")
plt.xlabel("No. of intervals or the distance multiplied by 10")